version: '3.5'

services:
  kafka:
    hostname: kafka
    image: spotify/kafka    
    networks:
      development:
        aliases:
          - kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"

networks:
  development:
    name: development