version: '3'

services:
  shop-ui:
    image: dockerton/shop-ui:latest
    ports:
    - 57010:80
    environment:
    - RECOMMENDATION_SERVICE_URL=http://recommendations:80
    - CRM_SERVICE_URL=http://crm:80
    - ORDER_SERVICE_URL=http://orders:80
    depends_on:
    - recommendations
    - crm
    - orders

  recommendations:
    image: dockerton/recommendations:latest
    ports:
    - 57011:80

  crm:
    image: dockerton/crm:latest
    ports:
    - 57012:80

  orders:
    image: dockerton/orders:latest
    ports:
    - 57013:80        