swagger: "2.0"
info:
  version: 0.0.1
  title: Customer relationship management API

paths:
  /api/customers/{id}:
      get:
        summary: Returns information about a given customer
        tags:
          - Customers
        parameters:
          - name: id
            in: path
            required: true
            type: string
        responses:
          200:
            description: OK
            schema:
              $ref: "#/definitions/customer"

definitions:
  customer:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      email:
        type: string
      imageUrl:
        type: string
      address:
        $ref: "#/definitions/address"
      
  address:
    type: object
    properties:
      streetname:
        type: string
      zipcode:
        type: string
      city:
        type: string
